### ISSUE TITLE
Links to languages don't work

### ISSUE THREAD

**Issue by andrewhamon** [keonkim/awesome-nlp#2]
Since the languages section is a nested list, the references to individual languages are currently useless. AFAIF only headers can be linked to.

**Comment by keonkim** [comment]
I think link fixes in #3 and #4 are also a good way to go (giving ids to nested lists) Any idea what we should decide on?

**Comment by keonkim** [comment]
I wanted to keep nested lists, so I merged #4 Thanks for the PR!
