### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by diasks2** [keonkim/awesome-nlp#9]
Great resource, thanks for creating this! I noticed that you don't have any Ruby libraries listed. I maintain a list of Ruby NLP libraries that you could link to if you like: https://github.com/diasks2/ruby-nlp

**Comment by keonkim** [comment]
Wow that is a really solid list!
I just a made link to your repository, since you maintain ruby libraries list much better than us.

**Comment by diasks2** [comment]
Thanks!
